Update StringComparisons
added hamming comparison

diff --git a/StringComparisons b/StringComparisons
--- a/StringComparisons
+++ b/StringComparisons
@@ -1,6 +1,9 @@
 #!/bin/zsh
 
 
+## levenshtein comparison
+######
+
 function string:compare:levenshtein {
     local Str1="$1"
     local Str2="$2"
@@ -42,8 +45,36 @@ function string:compare:levenshtein {
 }
 
 # examples
-
-~ string:compare:levenshtein sitting kitten              
+~% string:compare:levenshtein sitting kitten              
 # 3
-~ string:compare:levenshtein cat mat               
+~% string:compare:levenshtein cat mat               
 # 1
+
+
+## hamming comparison
+######
+
+function string:compare:hamming {
+    local Str1="$1"
+    local Str2="$2"
+    local StrLen=${#Str1}
+
+    if [[ ${#Str2} -ne ${StrLen} ]] { 
+        echo "Error: Strings must have equal length" >&2
+        return 1
+    }
+
+    local Distance=$StrLen
+    for I ( {1..$StrLen} ) {
+        (( Distance -= ${(N)Str1[$I]:#${Str2[$I]}} ))
+    }
+    echo $Distance
+}
+
+# examples
+~% string:compare:hamming cat hat   
+# 1
+~% string:compare:hamming kitten sit-in
+# 3
+~% string:compare:hamming announce denounce
+# 2
